### ISSUE TITLE
Social media icons fall off the side of the screen

### ISSUE THREAD

**Issue by choldgraf** [scientific-python/scientific-python.org#299]
### Please describe the bug or issue including how to reproduce it.

The social media icons on scientific-python.org spill off the side of the screen:

![image](https://user-images.githubusercontent.com/1839645/187179881-d14edacb-a2e0-4ca9-9000-df17814e78a5.png)

### Add any other context about the problem here, screenshots, etc.

Here are some minimal CSS rules that fixed this for me:

```css
.social-media-icons {
    display: flex;
    flex-wrap: wrap;
    gap: 0.2em;
}
```

![image](https://user-images.githubusercontent.com/1839645/187179848-db448f84-8128-444e-888c-0a71ce924254.png)
